const SHIPPING_PROTECTION_PRICE_DEFAULT = 1.99
const SHIPPING_PROTECTION_PRICES_NG = ['2.99', '5.99', '7.99']
const SHIPPING_PROTECTION_PRICES_NON_NG = ['1.99', '2.99','1.99', '2.99']

export {
    SHIPPING_PROTECTION_PRICE_DEFAULT,
    SHIPPING_PROTECTION_PRICES_NG,
    SHIPPING_PROTECTION_PRICES_NON_NG
}